const DB_Connection = require("../database/db");
const { runWithLogging } = require("../utils/runWithLogging");

const table_query = `
    -- ENUMs
    CREATE TYPE student_status_enum AS ENUM ('Active', 'Graduated', 'Paused');
    CREATE TYPE course_type_enum AS ENUM ('Theory', 'Lab');
    CREATE TYPE enrollment_status_enum AS ENUM ('Pending', 'Enrolled', 'Withdrawn');
    CREATE TYPE marking_type_enum AS ENUM ('Midterm', 'Final');
    CREATE TYPE marking_status_enum AS ENUM ('Published', 'Draft');
    CREATE TYPE payment_method_enum AS ENUM ('Mobile Banking', 'Bank Transfer');
    CREATE TYPE payment_status_enum AS ENUM ('Paid', 'Partial', 'Overdue');
    CREATE TYPE appointment_type_enum AS ENUM ('Lecturer', 'Assistant Professor', 'Associate Professor', 'Professor');

    CREATE TABLE users (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        mobile_number VARCHAR(20),
        mobile_banking_number VARCHAR(20),
        bank_account_number VARCHAR(50),
        permanent_address TEXT,
        present_address TEXT,
        birth_reg_number VARCHAR(50),
        nid_number VARCHAR(50),
        passport_number VARCHAR(50),
        birth_date DATE,
        emergency_contact_name VARCHAR(255),
        emergency_contact_number VARCHAR(20),
        emergency_contact_relation VARCHAR(50)
    );

    CREATE TABLE departments (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        code VARCHAR(20) UNIQUE,
        name VARCHAR(255) NOT NULL,
        department_head_id INT
    );

    CREATE TABLE teachers (
        user_id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        appointment appointment_type_enum,
        official_mail VARCHAR(255),
        department_id INT REFERENCES departments(id)
    );

    CREATE TABLE students (
        user_id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        roll_number VARCHAR(20) UNIQUE NOT NULL,
        official_mail VARCHAR(255),
        status student_status_enum DEFAULT 'Active'
    );
    ALTER TABLE departments 
    ADD CONSTRAINT fk_dept_head 
    FOREIGN KEY (department_head_id) REFERENCES teachers(user_id);

    CREATE TABLE terms (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        term_number INT NOT NULL,
        start_date DATE NOT NULL,
        end_date DATE NOT NULL,
        department_id INTEGER REFERENCES departments(id)
    );

    CREATE TABLE courses (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        course_code VARCHAR(20) UNIQUE, 
        name VARCHAR(255) NOT NULL,
        credit_hours DECIMAL(3, 1) NOT NULL,
        type course_type_enum,
        department_id INTEGER REFERENCES departments(id)
    );

    CREATE TABLE course_prerequisites (
        course_id INTEGER REFERENCES courses(id),
        prereq_id INTEGER REFERENCES courses(id),
        PRIMARY KEY (course_id, prereq_id)
    );

    CREATE TABLE course_offerings (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        term_id INT REFERENCES terms(id),
        course_id INTEGER REFERENCES courses(id),
        max_capacity INT,
        UNIQUE(term_id, course_id)
    );

    CREATE TABLE sections (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(50), 
        course_offering_id INT REFERENCES course_offerings(id),
        teacher_id INT REFERENCES teachers(user_id)
    );

    CREATE TABLE student_advisor_history (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        student_id INT REFERENCES students(user_id),
        teacher_id INT REFERENCES teachers(user_id),
        start_date DATE,
        end_date DATE,
        change_reason TEXT
    );

    CREATE TABLE student_enrollments (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        student_id INT REFERENCES students(user_id),
        course_offering_id INT REFERENCES course_offerings(id),
        credit_when_taking DECIMAL(3, 1),
        status enrollment_status_enum DEFAULT 'Pending',
        enrollment_timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        approved_timestamp TIMESTAMPTZ,
        grade VARCHAR(5),
        is_retake BOOLEAN DEFAULT FALSE,
        approved_by_teacher_id INT REFERENCES teachers(user_id)
    );

    CREATE TABLE marking_components (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        enrollment_id INT REFERENCES student_enrollments(id) ON DELETE CASCADE,
        type marking_type_enum,
        total_marks DECIMAL(5, 2),
        marks_obtained DECIMAL(5, 2),
        status marking_status_enum DEFAULT 'Draft'
    );

    CREATE TABLE dues (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(100), 
        amount DECIMAL(10, 2) NOT NULL,
        bank_account_number VARCHAR(50) 
    );

    CREATE TABLE student_dues_payment (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        student_id INT REFERENCES students(user_id),
        due_id INT REFERENCES dues(id),
        amount_paid DECIMAL(10, 2) DEFAULT 0,
        paid_at TIMESTAMPTZ,
        payment_method payment_method_enum,
        mobile_banking_number VARCHAR(20),
        status payment_status_enum DEFAULT 'Overdue',
        deadline DATE
    );

    CREATE TABLE feedback (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        term_id INT REFERENCES terms(id),
        course_id INT REFERENCES courses(id),
        teacher_id INT REFERENCES teachers(user_id), 
        csv_file_url TEXT,
        average_rating DECIMAL(3, 2)
    );
`

class TableModel {
    constructor() {
        this.db = DB_Connection.getInstance();
    }

    initalizeTables = async () => {
        return await runWithLogging(
            'Table Creation',
            async () => {
                const result = await this.db.query_executor(table_query);
                return result;
            }
        );
    }
}

module.exports = new TableModel();