const DB_Connection = require("../database/db.js");
const { runWithLogging } = require("../utils/runWithLogging.js");

const table_query = `
    -- ENUMs
    DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'student_status_enum') THEN
            CREATE TYPE student_status_enum AS ENUM ('Active', 'Graduated', 'Paused');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'course_type_enum') THEN
            CREATE TYPE course_type_enum AS ENUM ('Theory', 'Lab');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'enrollment_status_enum') THEN
            CREATE TYPE enrollment_status_enum AS ENUM ('Pending', 'Enrolled', 'Withdrawn');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'marking_type_enum') THEN
            CREATE TYPE marking_type_enum AS ENUM ('Midterm', 'Final');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'marking_status_enum') THEN
            CREATE TYPE marking_status_enum AS ENUM ('Published', 'Draft');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_method_enum') THEN
            CREATE TYPE payment_method_enum AS ENUM ('Mobile Banking', 'Bank Transfer');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'payment_status_enum') THEN
            CREATE TYPE payment_status_enum AS ENUM ('Paid', 'Partial', 'Overdue');
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'appointment_type_enum') THEN
            CREATE TYPE appointment_type_enum AS ENUM ('Lecturer', 'Assistant Professor', 'Associate Professor', 'Professor');
        END IF;
    END $$;

    CREATE TABLE IF NOT EXISTS users (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(255) NOT NULL,
        email VARCHAR(255) UNIQUE NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        role VARCHAR(20) DEFAULT 'Student',
        refresh_token TEXT,
        mobile_number VARCHAR(20),
        mobile_banking_number VARCHAR(20),
        bank_account_number VARCHAR(50),
        permanent_address TEXT,
        present_address TEXT NOT NULL,
        birth_reg_number VARCHAR(50) NOT NULL,
        nid_number VARCHAR(50),
        passport_number VARCHAR(50),
        birth_date DATE NOT NULL,
        emergency_contact_name VARCHAR(255),
        emergency_contact_number VARCHAR(20) NOT NULL,
        emergency_contact_relation VARCHAR(50),
        CONSTRAINT payment_constraint CHECK (bank_account_number IS NOT NULL OR mobile_banking_number IS NOT NULL),
        CONSTRAINT identification_constraint CHECK (passport_number IS NOT NULL OR nid_number IS NOT NULL)
    );

    CREATE TABLE IF NOT EXISTS departments (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        code VARCHAR(20) UNIQUE,
        name VARCHAR(255) NOT NULL,
        department_head_id INT
    );

    CREATE TABLE IF NOT EXISTS terms (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        term_number INT NOT NULL,
        start_date DATE NOT NULL,
        end_date DATE NOT NULL,
        department_id INTEGER REFERENCES departments(id) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS teachers (
        user_id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        appointment appointment_type_enum,
        official_mail VARCHAR(255),
        department_id INT REFERENCES departments(id)
    );

    CREATE TABLE IF NOT EXISTS students (
        user_id INT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
        roll_number VARCHAR(20) UNIQUE NOT NULL,
        official_mail VARCHAR(255),
        status student_status_enum DEFAULT 'Active',
        current_term INTEGER REFERENCES terms(id)
    );

    CREATE TABLE IF NOT EXISTS department_heads (
        department_id INTEGER REFERENCES departments(id),
        teacher_id INTEGER REFERENCES teachers(user_id),
        CONSTRAINT dept_head_pk PRIMARY KEY (department_id, teacher_id)
    );

    CREATE TABLE IF NOT EXISTS student_term_history (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        student_id INTEGER REFERENCES students(user_id) ON DELETE CASCADE,
        term_id INTEGER REFERENCES terms(id) ON DELETE CASCADE,
        start_date DATE,
        end_date DATE
    );

    CREATE TABLE IF NOT EXISTS courses (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        course_code VARCHAR(20) UNIQUE NOT NULL, 
        name VARCHAR(255) NOT NULL,
        credit_hours DECIMAL(3, 1) NOT NULL,
        type course_type_enum,
        department_id INTEGER REFERENCES departments(id) NOT NULL
    );

    CREATE TABLE IF NOT EXISTS course_prerequisites (
        course_id INTEGER REFERENCES courses(id),
        prereq_id INTEGER REFERENCES courses(id),
        PRIMARY KEY (course_id, prereq_id)
    );

    CREATE TABLE IF NOT EXISTS course_offerings (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        term_id INT REFERENCES terms(id) NOT NULL,
        course_id INTEGER REFERENCES courses(id) NOT NULL,
        max_capacity INT,
        UNIQUE(term_id, course_id)
    );

    CREATE TABLE IF NOT EXISTS sections (
        term_id INTEGER REFERENCES terms(id), 
        name VARCHAR(50),
        UNIQUE(term_id, name)
    );

    CREATE TABLE IF NOT EXISTS teaches (
        course_offering_id INTEGER REFERENCES course_offerings(id),
        teacher_id INTEGER REFERENCES teachers(user_id),
        section_name VARCHAR(50)
    );

    CREATE TABLE IF NOT EXISTS student_sections (
        student_id INTEGER REFERENCES students(user_id),
        section_name VARCHAR(50)
    );

    CREATE TABLE IF NOT EXISTS student_advisor_history (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        student_id INT REFERENCES students(user_id),
        teacher_id INT REFERENCES teachers(user_id),
        start_date DATE,
        end_date DATE,
        change_reason TEXT
    );

    CREATE TABLE IF NOT EXISTS student_enrollments (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        student_id INT REFERENCES students(user_id),
        course_offering_id INT REFERENCES course_offerings(id),
        credit_when_taking DECIMAL(3, 1),
        status enrollment_status_enum DEFAULT 'Pending',
        enrollment_timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        approved_timestamp TIMESTAMPTZ,
        grade VARCHAR(5),
        is_retake BOOLEAN DEFAULT FALSE,
        approved_by_teacher_id INT REFERENCES teachers(user_id)
    );

    CREATE TABLE IF NOT EXISTS marking_components (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        enrollment_id INT REFERENCES student_enrollments(id) ON DELETE CASCADE,
        type marking_type_enum,
        total_marks DECIMAL(5, 2),
        marks_obtained DECIMAL(5, 2),
        status marking_status_enum DEFAULT 'Draft'
    );

    CREATE TABLE IF NOT EXISTS dues (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(100), 
        amount DECIMAL(10, 2) NOT NULL,
        bank_account_number VARCHAR(50) 
    );

    CREATE TABLE IF NOT EXISTS student_dues_payment (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        student_id INT REFERENCES students(user_id),
        due_id INT REFERENCES dues(id),
        amount_paid DECIMAL(10, 2) DEFAULT 0,
        paid_at TIMESTAMPTZ,
        payment_method payment_method_enum,
        mobile_banking_number VARCHAR(20),
        status payment_status_enum DEFAULT 'Overdue',
        deadline DATE
    );

    CREATE TABLE IF NOT EXISTS feedback (
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        course_offering_id INTEGER REFERENCES course_offerings(id),
        teacher_id INT REFERENCES teachers(user_id), 
        csv_file_url TEXT,
        average_rating DECIMAL(3, 2)
    );
`

class TableModel {
    constructor() {
        this.db = DB_Connection.getInstance();
    }

    initalizeTables = async () => {
        return await runWithLogging(
            'Table Creation',
            async () => {
                const result = await this.db.query_executor(table_query);
                return result;
            }
        );
    }

    testConnection = async (req, res)=>{
        const query =' SELECT 1 ;'
        return await runWithLogging(
            'DB connection test',
            async()=>{
                const result = await this.db.query_executor(query);
                return result ;
            }
        )
    }
}

module.exports = TableModel;