-- Phase 1 migration: rule-ready dues schema (backward-compatible)

DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'due_frequency_enum') THEN
        CREATE TYPE due_frequency_enum AS ENUM ('per_term', 'per_year', 'one_time');
    END IF;
END $$;

ALTER TABLE dues
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS required_for_registration BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE student_dues_payment
ADD COLUMN IF NOT EXISTS amount_due_override DECIMAL(10, 2),
ADD COLUMN IF NOT EXISTS term_id INT REFERENCES terms(id),
ADD COLUMN IF NOT EXISTS issued_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS due_date DATE,
ADD COLUMN IF NOT EXISTS required_for_registration BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS waived_at TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS waive_reason TEXT;

CREATE INDEX IF NOT EXISTS idx_student_dues_blocking_lookup
    ON student_dues_payment (student_id, term_id, required_for_registration, status);

CREATE INDEX IF NOT EXISTS idx_student_dues_due_date
    ON student_dues_payment (due_date);

CREATE TABLE IF NOT EXISTS due_rules (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    due_id INT REFERENCES dues(id) ON DELETE CASCADE,
    frequency due_frequency_enum NOT NULL DEFAULT 'per_year',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    required_for_registration BOOLEAN NOT NULL DEFAULT TRUE,
    issue_offset_days INT NOT NULL DEFAULT 7,
    starts_on DATE,
    ends_on DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT due_rules_window_chk CHECK (starts_on IS NULL OR ends_on IS NULL OR starts_on <= ends_on)
);

CREATE TABLE IF NOT EXISTS due_rule_scopes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rule_id INT NOT NULL REFERENCES due_rules(id) ON DELETE CASCADE,
    department_id INT REFERENCES departments(id),
    term_number INT,
    section_name VARCHAR(50),
    batch_year INT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_due_rule_scopes_match
    ON due_rule_scopes (rule_id, department_id, term_number, section_name, batch_year);

CREATE TABLE IF NOT EXISTS due_rule_amount_overrides (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rule_id INT NOT NULL REFERENCES due_rules(id) ON DELETE CASCADE,
    department_id INT REFERENCES departments(id),
    term_number INT,
    section_name VARCHAR(50),
    batch_year INT,
    override_amount DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_due_rule_amount_overrides_match
    ON due_rule_amount_overrides (rule_id, department_id, term_number, section_name, batch_year);

CREATE TABLE IF NOT EXISTS due_rule_issuance_log (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    rule_id INT REFERENCES due_rules(id) ON DELETE SET NULL,
    student_id INT NOT NULL REFERENCES students(user_id) ON DELETE CASCADE,
    term_id INT REFERENCES terms(id) ON DELETE SET NULL,
    student_due_payment_id INT REFERENCES student_dues_payment(id) ON DELETE SET NULL,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (rule_id, student_id, term_id)
);
